update readme
Monadical-SAS/Morpheus pull request #169
Opened 2023-10-19 21:06 UTC by asanchezyali

2023-10-20 02:06 UTC, juanArias8 approved these changes

2023-10-20 21:09 UTC, curibe requested changes

2023-10-20 21:09 UTC, curibe commented on README.md
>  docker-compose build client
@asanchezyali please remove the dash from all parts where you find it, in docker compose:   docker-compose -> docker compose

2023-10-20 21:09 UTC, curibe commented on README.md
> +## Adding a new dependency to the frontend
Don't remove '#' symbol. This is a heading3, not a heading2

2023-10-20 21:09 UTC, curibe commented on README.md
> +* To migrate or update to the head: `docker-compose run --rm datalib alembic upgrade head`.
@asanchezyali please change from inline-code to block-code(with three quote marks). It allows one to copy the command more easily, especially for long commands. Please do the same in other parts of the REAMDE where it is required

2023-10-20 21:12 UTC, curibe requested changes

2023-10-20 21:12 UTC, curibe commented on README.md
>  docker-compose build client
@asanchezyali please remove the dash from all parts where you find it, in docker compose: docker-compose -> docker compose

2023-10-23 21:38 UTC, curibe approved these changes

2023-10-24 03:56 UTC, merged